/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9XnVa7VpKhL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Crimson_Text } from 'next/font/google'
import { Judson } from 'next/font/google'

crimson_text({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

'use client';
import Link from "next/link"
import { JSX, SVGProps } from "react"
import { HoverEffect } from "@/components/ui/card-hover-effect"
import SignupFormDemo from "./example/signup-form-demo";
import { AnimatedModalDemo } from "./example/animated-modal-demo";

export function landing() {
  return (
    
    <main className="flex-1 ">
          <section className="w-full relative overflow-hidden">
      <video
        autoPlay
        loop
        muted
        playsInline
        className="absolute top-0 left-0 w-full h-full object-cover z-0 opacity-75"
      >
        <source src="https://emcstrategygroup.com/wp-content/uploads/2023/07/US-Capitol-Rotunda.mp4" type="video/mp4" />
        Your browser does not support the video tag.
      </video>
      <div className="relative z-10 bg-black bg-opacity-50 py-12 md:py-24 lg:py-32">
        <div className="container px-4 md:px-6 mx-auto">
          <div className="grid gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_600px]">
            <div className="flex flex-col justify-center space-y-4">
              <div className="space-y-2">
                <h1 className="text-3xl font-bold tracking-tighter sm:text-5xl xl:text-6xl/none text-white">
                  Trusted Government Relations and Business Development
                </h1>
                <p className="max-w-[600px] text-white md:text-xl">
                  EMC Strategy Group provides expert services in government relations, external affairs,
                  workplace training, and business/economic development to help organizations navigate the
                  complexities of the public sector.
                </p>
              </div>
              <div className="flex flex-col gap-2 min-[400px]:flex-row">
                <AnimatedModalDemo />
                <Link
                  href="#"
                  className="inline-flex h-10 items-center justify-center rounded-md border border-white bg-transparent px-8 text-sm font-medium text-white shadow-sm transition-colors hover:bg-white hover:text-black focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
                  prefetch={false}
                >
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section id="services" className="w-full py-12 md:py-24 lg:py-32 border-t">
    <div className="flex flex-col items-center justify-center space-y-4 text-center">
      <div className="space-y-2">
        <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Our Services</div>
          <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Expertise Across the Public Sector</h2>
          <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            EMC Strategy Group offers a comprehensive suite of services to help organizations navigate the
            complexities of the public sector, from government relations and external affairs to workplace
            training and business/economic development.
          </p>
        </div>
        <div className="max-w-5xl mx-auto px-8">
          <HoverEffect items={projects} />
        </div>
      </div>
    </section>
    
    <section id="clients" className="w-full py-12 md:py-24 lg:py-32 border-t">
      <div className="container px-4 md:px-6 mx-auto flex flex-col items-center">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Our Clients</div>
            <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
              Trusted by Organizations Across the Public Sector
            </h2>
            <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
              EMC Strategy Group has a proven track record of delivering successful outcomes for a diverse
              range of clients, including city, county, and state governments, federal agencies, and nonprofit
              organizations.
            </p>
          </div>
        </div>
        <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-3 lg:gap-12">
          <div className="flex flex-col justify-center space-y-4">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">City Governments</div>
            <ul className="grid gap-4">
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <MapIcon className="h-6 w-6" />
                  <span>City of Acme</span>
                </Link>
              </li>
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <MapIcon className="h-6 w-6" />
                  <span>City of Metropolis</span>
                </Link>
              </li>
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <MapIcon className="h-6 w-6" />
                  <span>City of Utopia</span>
                </Link>
              </li>
            </ul>
          </div>
          <div className="flex flex-col justify-center space-y-4">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">County Governments</div>
            <ul className="grid gap-4">
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <FlagIcon className="h-6 w-6" />
                  <span>Acme County</span>
                </Link>
              </li>
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <FlagIcon className="h-6 w-6" />
                  <span>Metropolis County</span>
                </Link>
              </li>
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <FlagIcon className="h-6 w-6" />
                  <span>Utopia County</span>
                </Link>
              </li>
            </ul>
          </div>
          <div className="flex flex-col justify-center space-y-4">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">State & Federal Governments</div>
            <ul className="grid gap-4">
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <FlagIcon className="h-6 w-6" />
                  <span>State of Acme</span>
                </Link>
              </li>
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <FlagIcon className="h-6 w-6" />
                  <span>U.S. Department of Commerce</span>
                </Link>
              </li>
              <li>
                <Link href="#" className="flex items-center gap-2 hover:underline" prefetch={false}>
                  <DonutIcon className="h-6 w-6" />
                  <span>Acme Nonprofit Foundation</span>
                </Link>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </section>
    <section id="about" className="w-full py-12 md:py-24 lg:py-32 border-t">
      <div className="container px-4 md:px-6 mx-auto flex flex-col items-center">
        <div className="grid gap-10 sm:px-10 md:gap-16 md:grid-cols-2">
          <div className="space-y-4">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">About Us</div>
            <h2 className="lg:leading-tighter text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl xl:text-[3.4rem] 2xl:text-[3.75rem]">
              Trusted Experts in Government Relations and Business Development
            </h2>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed">
              EMC Strategy Group is a leading provider of government relations, external affairs, workplace
              training, and business/economic development services. Our team of experienced professionals has a
              proven track record of delivering successful outcomes for a diverse range of clients, including city,
              county, and state governments, federal agencies, and nonprofit organizations.
            </p>
            <Link
              href="#"
              className="inline-flex h-9 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Contact Us
            </Link>
          </div>
          <div className="flex flex-col items-start space-y-4">
            <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Our Approach</div>
            <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed">
              At EMC Strategy Group, we take a collaborative and strategic approach to helping our clients
              navigate the complexities of the public sector. We leverage our deep relationships and expertise to
              effectively advocate for our clients interests, develop and execute communication plans, provide
              customized training programs, and assist with securing funding opportunities and fostering
              partnerships.
            </p>
            <Link
              href="#"
              className="inline-flex h-9 items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              prefetch={false}
            >
              Learn More
            </Link>
          </div>
        </div>
      </div>
    </section>
    <section id="testimonials" className="w-full py-12 md:py-24 lg:py-32 border-t">
      <div className="container px-4 md:px-6 mx-auto flex flex-col items-center">
        <div className="space-y-4 text-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl">What Our Clients Say</h2>
              <p className="mx-auto max-w-[600px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Hear from the government agencies and nonprofit organizations we&apos;ve had the privilege of serving.
              </p>
            </div>
            <div className="mx-auto grid max-w-5xl gap-6 py-12 sm:grid-cols-2 md:grid-cols-3">
              <div className="rounded-lg border bg-background p-6 shadow-sm">
                <blockquote className="flex flex-col justify-between space-y-4">
                  <div>
                    <p className="text-lg font-medium leading-relaxed">
                      &ldquo;EMC Strategy Group has been an invaluable partner in helping us navigate the complex
                      political landscape and achieve our policy goals.&rdquo;
                    </p>
                  </div>
                  <footer className="text-sm text-muted-foreground">
                    - John Doe, Director of Government Affairs, City of Exampleville
                  </footer>
                </blockquote>
              </div>
              <div className="rounded-lg border bg-background p-6 shadow-sm">
                <blockquote className="flex flex-col justify-between space-y-4">
                  <div>
                    <p className="text-lg font-medium leading-relaxed">
                      &ldquo;The training programs provided by EMC Strategy Group have been instrumental in
                      developing the skills and knowledge of our staff, enabling us to better serve our constituents.&rdquo;
                    </p>
                  </div>
                  <footer className="text-sm text-muted-foreground">
                    - Jane Smith, Executive Director, Nonprofit Organization
                  </footer>
                </blockquote>
              </div>
              <div className="rounded-lg border bg-background p-6 shadow-sm">
                <blockquote className="flex flex-col justify-between space-y-4">
                  <div>
                    <p className="text-lg font-medium leading-relaxed">
                      &ldquo;EMC Strategy Group has been instrumental in helping us drive economic development and
                      support local businesses in our community. Their expertise and guidance have been invaluable.&rdquo;
                    </p>
                  </div>
                  <footer className="text-sm text-muted-foreground">
                    - Michael Johnson, Economic Development Director, County of Exampleville
                  </footer>
                </blockquote>
              </div>
            </div>
          </div>
        </section>
        <section id="internship" className="w-full py-12 md:py-24 lg:py-32 border-t">
          <div className="container px-4 md:px-6 mx-auto flex flex-col items-center">
            <div className="flex flex-col items-center justify-center space-y-4 text-center">
              <div className="space-y-2">
                <div className="inline-block rounded-lg bg-muted px-3 py-1 text-sm">Internship Program</div>
                <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
                  Government Relations Internship/Fellowship
                </h2>
                <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                  EMC Strategy Group offers a competitive internship and fellowship program for students and
                  recent graduates interested in pursuing a career in government relations, public policy, or public
                  affairs. Interns and fellows will have the opportunity to work alongside our experienced team, gain
                  hands-on experience, and develop valuable skills in areas such as advocacy, stakeholder engagement,
                  and policy analysis.
                </p>
                <div className="flex" />
                <SignupFormDemo />
              </div>
            </div>
          </div>
        </section>
    
  </main>
      
  )
}


function MapIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.106 5.553a2 2 0 0 0 1.788 0l3.659-1.83A1 1 0 0 1 21 4.619v12.764a1 1 0 0 1-.553.894l-4.553 2.277a2 2 0 0 1-1.788 0l-4.212-2.106a2 2 0 0 0-1.788 0l-3.659 1.83A1 1 0 0 1 3 19.381V6.618a1 1 0 0 1 .553-.894l4.553-2.277a2 2 0 0 1 1.788 0z" />
      <path d="M15 5.764v15" />
      <path d="M9 3.236v15" />
    </svg>
  )
}

function FlagIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z" />
      <line x1="4" x2="4" y1="22" y2="15" />
    </svg>
  )
}

function DonutIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20.5 10a2.5 2.5 0 0 1-2.4-3H18a2.95 2.95 0 0 1-2.6-4.4 10 10 0 1 0 6.3 7.1c-.3.2-.8.3-1.2.3" />
      <circle cx="12" cy="12" r="3" />
    </svg>
  )
}

export const projects = [
  {
    title: "Government Relations",
    description:
      "Leverage our deep relationships and expertise to effectively advocate for your organization's interests at the local, state, and federal levels.",
    link: "",
  },
  {
    title: "External Affairs",
    description:
      "Develop and execute strategic communication plans to build and maintain positive relationships with key stakeholders, including the media, community organizations, and the public.",
    link: "",
  },
  {
    title: "Workplace Training",
    description:
      "Provide customized training programs to help your employees navigate the complexities of the public sector, from understanding government processes to effective communication and collaboration.",
    link: "",
  },
  {
    title: "Business/Economic Development",
    description:
      "Assist organizations in identifying and securing funding opportunities, navigating regulatory requirements, and fostering partnerships to drive economic growth and development.",
    link: "",
  },
  {
    title: "Non-Profit Management",
    description:
      "Led by President & CEO Ernie Gonzalez, Jr., EMC excels in guiding diverse non-profit organizations across the nation, maximizing their impact and efficiency. ",
    link: "",
  },
  {
    title: "Political Campaign Management",
    description: "EMC crafts winning strategies and builds comprehensive campaign organizations, empowering candidates to achieve electoral success.",
    link: "",
  },
];